/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0ee752c2-2bc9-4a89-8eba-6f494fca2399",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_83BRdmesY",
    "aws_user_pools_web_client_id": "5q9ba503vomt40pq54iibmmpk8",
    "oauth": {}
};


export default awsmobile;
